force-app/main/default/objects/Blackhawk_API_Settings__c/Blackhawk_API_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Blackhawk API Settings</label>
</CustomObject>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Catalog_API_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Catalog_API_Endpoint__c</fullName>
    <label>Catalog API Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Client_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Certificate_Name__c</fullName>
    <label>Client Certificate Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Client_Program_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Program_Id__c</fullName>
    <label>Client Program Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Milliseconds_To_Wait__c.field-meta.xml
<CustomField>
    <fullName>Milliseconds_To_Wait__c</fullName>
    <label>Milliseconds To Wait</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Monitoring_Status_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Monitoring_Status_Endpoint__c</fullName>
    <label>Monitoring Status Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Real_time_eGift_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Real_time_eGift_Endpoint__c</fullName>
    <label>Real-time eGift Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Return_Card_Number_and_PIN__c.field-meta.xml
<CustomField>
    <fullName>Return_Card_Number_and_PIN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Return Card Number and PIN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/SYNCHRONOUS_ONLY__c.field-meta.xml
<CustomField>
    <fullName>SYNCHRONOUS_ONLY__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SYNCHRONOUS ONLY</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/Blackhawk_Card_Product__c.object-meta.xml
<CustomObject>
    <description>The Hawk Marketplace Rewards Catalog Processing API allows you to access the catalog of card products that have been made available for you to order.

The card catalog is specifically configured to your sub-organization and client programs in the Hawk Marketplace platform. It is not a global catalog of all products available from Blackhawk Network. If you do not see a product you believe should be available for you to order, or you would like to add a new product to your catalog, reach out to your Account Manager.</description>
    <label>Blackhawk Catalog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blackhawk Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Client_Program_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Program_Id__c</fullName>
    <description>clientProgramId</description>
    <label>Client Program Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Content_Provider_Code__c.field-meta.xml
<CustomField>
    <fullName>Content_Provider_Code__c</fullName>
    <externalId>true</externalId>
    <label>Content Provider Code</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Locale__c.field-meta.xml
<CustomField>
    <fullName>Locale__c</fullName>
    <label>Locale</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Logo_Image__c.field-meta.xml
<CustomField>
    <fullName>Logo_Image__c</fullName>
    <label>Logo Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Parent_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Brand_Name__c</fullName>
    <label>Parent Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <description>programName</description>
    <label>Program Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <description>programType</description>
    <label>Program Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Redemption_Info__c.field-meta.xml
<CustomField>
    <fullName>Redemption_Info__c</fullName>
    <label>Redemption Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/TNC_Text__c.field-meta.xml
<CustomField>
    <fullName>TNC_Text__c</fullName>
    <label>Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/TNC_Type__c.field-meta.xml
<CustomField>
    <fullName>TNC_Type__c</fullName>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/VR_Maximum__c.field-meta.xml
<CustomField>
    <fullName>VR_Maximum__c</fullName>
    <label>Maximum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/VR_Minimum__c.field-meta.xml
<CustomField>
    <fullName>VR_Minimum__c</fullName>
    <label>Minimum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BlackhawkApi.cls
public class BlackhawkApi {

    public Blackhawk_API_Settings__c bhAPISetting = new Blackhawk_API_Settings__c();

    public BlackhawkApi(){
        bhAPISetting = getActiveBlackhawkApiSetting();
    }

    public void rewardsMonitoring(){
        System.debug('bhAPISetting >>> '+bhAPISetting);
        Http httpInstance = new Http();
        HttpRequest httpRequestInstance = new HttpRequest();
        httpRequestInstance.setEndpoint('callout:BlackhawkAPI'+bhAPISetting.Monitoring_Status_Endpoint__c);///rewardsOrderProcessing/v1/monitor');
        httpRequestInstance.setClientCertificateName(bhAPISetting.Client_Certificate_Name__c);
        httpRequestInstance.setHeader('Content-Type','application/json');
        httpRequestInstance.setHeader('Merchantid',bhAPISetting.Merchant_Id__c);
        httpRequestInstance.setHeader('Requestid',String.valueOf(DateTime.now().millisecond()));
        httpRequestInstance.setMethod('GET');
        HttpResponse httpResponse = httpInstance.send(httpRequestInstance);  
        System.debug(httpResponse.getBody());
    }

    public void getCatalogByKey(String clientProgramId){
        Http httpInstance = new Http();
        HttpRequest httpRequestInstance = new HttpRequest();
        httpRequestInstance.setEndpoint('callout:BlackhawkAPI'+bhAPISetting.Catalog_API_Endpoint__c+'?clientProgramId='+clientProgramId);//rewardsCatalogProcessing/v1/clientProgram/byKey'+'?clientProgramId='+clientProgramId);
        httpRequestInstance.setClientCertificateName(bhAPISetting.Client_Certificate_Name__c);
        httpRequestInstance.setHeader('Content-Type','application/json');
        httpRequestInstance.setHeader('Merchantid',bhAPISetting.Merchant_Id__c);
        httpRequestInstance.setHeader('Requestid',String.valueOf(DateTime.now().millisecond())); 
        httpRequestInstance.setMethod('GET');
        HttpResponse httpResponse = httpInstance.send(httpRequestInstance);  
        BlackhawkClientProgramWrapper bhcpWrapObj = BlackhawkClientProgramWrapper.parse(httpResponse.getBody());
        upsert generateBlackhawkCardProducts(bhcpWrapObj) Content_Provider_Code__c;
    }

    public void submitRealTimeEgiftBulk(){
        RealTimeEgiftBulkResponseWrapper rtebrWrap = new RealTimeEgiftBulkResponseWrapper();
        Http httpInstance = new Http();
        HttpRequest httpRequestInstance = new HttpRequest();
        httpRequestInstance.setTimeout(120000);
        httpRequestInstance.setEndpoint('callout:BlackhawkAPI'+bhAPISetting.Real_time_eGift_Endpoint__c);//rewardsOrderProcessing/v1/submitRealTimeEgiftBulk');
        httpRequestInstance.setClientCertificateName(bhAPISetting.Client_Certificate_Name__c);
        httpRequestInstance.setHeader('Content-Type','application/json');
        httpRequestInstance.setHeader('Merchantid',bhAPISetting.Merchant_Id__c);
        httpRequestInstance.setHeader('Requestid',String.valueOf(DateTime.now().millisecond()));
        httpRequestInstance.setHeader('millisecondsToWait',bhAPISetting.Milliseconds_To_Wait__c);
        httpRequestInstance.setHeader('SYNCHRONOUS_ONLY',String.valueOf(bhAPISetting.SYNCHRONOUS_ONLY__c));
        httpRequestInstance.setMethod('POST');
        httpRequestInstance.setBody(generateRequest(0,''));  
        HttpResponse httpResponse = httpInstance.send(httpRequestInstance);  
        System.debug(httpResponse.getStatusCode());
        System.debug(httpResponse.getBody());
        System.debug('rtebrWrap >>> '+rtebrWrap.parse(httpResponse.getBody()));
    }

    public String generateRequest(Decimal amount, String contentProvider){
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('clientProgramNumber', bhAPISetting.Client_Program_Id__c);
        gen.writeStringField('paymentType', bhAPISetting.Payment_Type__c);
        gen.writeStringField('returnCardNumberAndPIN', String.valueOf(bhAPISetting.Return_Card_Number_and_PIN__c));
        gen.writeFieldName('orderDetails');
        gen.writeStartArray();
        gen.writeStartObject();
        gen.writeStringField('clientRefId', String.valueOf(DateTime.now().millisecond()));
        gen.writeStringField('quantity', '1');
        gen.writeStringField('amount', '5.01');
        gen.writeStringField('contentProvider', 'IAGOnly1VirtualVisa_AUD_en_eGift');
        gen.writeEndObject();
        gen.writeEndArray();
        gen.writeEndObject();
        String pretty = gen.getAsString();
        System.debug(pretty);
        return pretty;
    }

    public class RealTimeEgiftBulkResponseWrapper{
        public String transactionId;	//435LYTF8GAS6NCB3R9TLCXWY30
        public boolean isCompleted;
        public Integer percentComplete;	//100
        public boolean success;
        public String orderNumber;	//401087978
        public String url;	//https://egiftpp.blackhawknetwork.com/egift?tid=657Q0RGVTJTZKC50AW2P8STYQC&gcm=n&gs=n&gw=n&eid=Z6BWA51S8BN9TZW4JPW719LNT8
        public String contentProviderCode;	//BestBuy_eGift
        public Decimal transactionAmount;	//25

        public RealTimeEgiftBulkResponseWrapper parse(String json){
            return (RealTimeEgiftBulkResponseWrapper) System.JSON.deserialize(json, RealTimeEgiftBulkResponseWrapper.class);
        }
    
    }

    public Blackhawk_API_Settings__c getActiveBlackhawkApiSetting (){
        return [SELECT  Id, Catalog_API_Endpoint__c, Client_Program_Id__c, Is_Active__c, Merchant_Id__c, 
                        Milliseconds_To_Wait__c, Monitoring_Status_Endpoint__c, Payment_Type__c, Real_time_eGift_Endpoint__c,
                        Return_Card_Number_and_PIN__c, SYNCHRONOUS_ONLY__c, Client_Certificate_Name__c
                FROM Blackhawk_API_Settings__c
                WHERE Is_Active__c = TRUE];
    }

    public List<Blackhawk_Card_Product__c> generateBlackhawkCardProducts (BlackhawkClientProgramWrapper blackhawkClientWrapObj){

        List<Blackhawk_Card_Product__c> blackHawkCardProductListToInsert = new List<Blackhawk_Card_Product__c>();

        if(blackhawkClientWrapObj.products.size() > 0){
            for(BlackhawkClientProgramWrapper.Products product : blackhawkClientWrapObj.products){
                Blackhawk_Card_Product__c bcp = new Blackhawk_Card_Product__c();
                bcp.Name = product.contentProviderCode;
                bcp.Client_Program_Id__c = blackhawkClientWrapObj.clientProgramId;
                bcp.Content_Provider_Code__c = product.contentProviderCode;
                bcp.Currency__c = blackhawkClientWrapObj.currency_Z;
                bcp.Locale__c = product.locale;
                bcp.Logo_Image__c = product.logoImage;
                bcp.VR_Maximum__c = product.valueRestrictions.maximum;
                bcp.VR_Minimum__c = product.valueRestrictions.minimum;
                bcp.Parent_Brand_Name__c = product.parentBrandName;
                bcp.Product_Description__c = product.productDescription;
                bcp.Product_Image__c = product.productImage;
                bcp.Product_Name__c = product.productName;
                bcp.Program_Name__c = blackhawkClientWrapObj.programName;
                bcp.Program_Type__c = blackhawkClientWrapObj.programType;
                bcp.Redemption_Info__c = blackhawkClientWrapObj.programType;
                bcp.TNC_Text__c = product.termsAndConditions.text;
                bcp.TNC_Type__c = product.termsAndConditions.type;
                blackHawkCardProductListToInsert.add(bcp);
            }
        }
        
        return blackHawkCardProductListToInsert;
    }
}