force-app/main/default/objects/Blackhawk_API_Settings__c/Blackhawk_API_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Blackhawk API Settings</label>
</CustomObject>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Catalog_API_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Catalog_API_Endpoint__c</fullName>
    <label>Catalog API Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Client_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Certificate_Name__c</fullName>
    <label>Client Certificate Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Client_Program_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Program_Id__c</fullName>
    <label>Client Program Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/eGift_Bulk_Code_Retrieval_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>eGift_Bulk_Code_Retrieval_Endpoint__c</fullName>
    <label>eGift Bulk Code Retrieval Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Maximum_Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Retry_Count__c</fullName>
    <label>Maximum Retry Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Milliseconds_To_Wait__c.field-meta.xml
<CustomField>
    <fullName>Milliseconds_To_Wait__c</fullName>
    <label>Milliseconds To Wait</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Monitoring_Status_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Monitoring_Status_Endpoint__c</fullName>
    <label>Monitoring Status Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Real_time_eGift_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Real_time_eGift_Endpoint__c</fullName>
    <label>Real-time eGift Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Return_Card_Number_and_PIN__c.field-meta.xml
<CustomField>
    <fullName>Return_Card_Number_and_PIN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Return Card Number and PIN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/SYNCHRONOUS_ONLY__c.field-meta.xml
<CustomField>
    <fullName>SYNCHRONOUS_ONLY__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SYNCHRONOUS ONLY</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/Blackhawk_Card_Product__c.object-meta.xml
<CustomObject>
    <description>The Hawk Marketplace Rewards Catalog Processing API allows you to access the catalog of card products that have been made available for you to order.

The card catalog is specifically configured to your sub-organization and client programs in the Hawk Marketplace platform. It is not a global catalog of all products available from Blackhawk Network. If you do not see a product you believe should be available for you to order, or you would like to add a new product to your catalog, reach out to your Account Manager.</description>
    <label>Blackhawk Catalog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blackhawk Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Client_Program_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Program_Id__c</fullName>
    <description>clientProgramId</description>
    <label>Client Program Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Content_Provider_Code__c.field-meta.xml
<CustomField>
    <fullName>Content_Provider_Code__c</fullName>
    <externalId>true</externalId>
    <label>Content Provider Code</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Locale__c.field-meta.xml
<CustomField>
    <fullName>Locale__c</fullName>
    <label>Locale</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Logo_Image__c.field-meta.xml
<CustomField>
    <fullName>Logo_Image__c</fullName>
    <label>Logo Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Parent_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Brand_Name__c</fullName>
    <label>Parent Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <description>programName</description>
    <label>Program Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <description>programType</description>
    <label>Program Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Redemption_Info__c.field-meta.xml
<CustomField>
    <fullName>Redemption_Info__c</fullName>
    <label>Redemption Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/TNC_Text__c.field-meta.xml
<CustomField>
    <fullName>TNC_Text__c</fullName>
    <label>Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/TNC_Type__c.field-meta.xml
<CustomField>
    <fullName>TNC_Type__c</fullName>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/VR_Maximum__c.field-meta.xml
<CustomField>
    <fullName>VR_Maximum__c</fullName>
    <label>Maximum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/VR_Minimum__c.field-meta.xml
<CustomField>
    <fullName>VR_Minimum__c</fullName>
    <label>Minimum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member_Benefit__c/Member_Benefit__c.object-meta.xml
<CustomObject>
    <label>Member Benefit</label>
    <nameField>
        <displayFormat>MB-{00000}</displayFormat>
        <label>Member Benefit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit__c/fields/Gift_Card_Request_Counter__c.field-meta.xml
<CustomField>
    <fullName>Gift_Card_Request_Counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Request Counter</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member_Benefit__c/fields/Member_Benefit_Program__c.field-meta.xml
<CustomField>
    <fullName>Member_Benefit_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Benefit Program</label>
    <referenceTo>Member_Benefit_Program__c</referenceTo>
    <relationshipLabel>Member Benefits</relationshipLabel>
    <relationshipName>Member_Benefits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit__c/fields/Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Request_Id__c</fullName>
    <label>Request Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/Member_Benefit_Program__c.object-meta.xml
<CustomObject>
    <label>Member Benefit Program</label>
    <nameField>
        <label>Member Benefit Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Benefit Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Blackhawk_Catalog_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Blackhawk_Catalog_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Blackhawk Catalog</label>
    <referenceTo>Blackhawk_Card_Product__c</referenceTo>
    <relationshipLabel>Member Benefit Programs</relationshipLabel>
    <relationshipName>Member_Benefit_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Gift_Card_Value__c.field-meta.xml
<CustomField>
    <fullName>Gift_Card_Value__c</fullName>
    <label>Gift Card Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BlackhawkAPIService.cls
/**
* @author: Rexie Aaron David
* @date: October 2023
* @description: This class handles all service logic for BlackhawkAPI
*/ 
public class BlackhawkAPIService {

    public static final String SUCCESSCODE = '201';
    public static final String SUCCESSEGIFTCODE = '200';
    public static final String RETRYSTATUSCODE = 'Status Code: 5';

    public class BlackhawkApiServiceException extends Exception {} 
    
    public static RealTimeEgiftBulkResponseWrapper submitRealTimeEgiftBulk(Member_Benefit__c memberBenefitRecord){

        LogException logger = new LogException();
        RealTimeEgiftBulkResponseWrapper rtebrWrap;
        try{
            memberBenefitRecord.Request_Id__c = memberBenefitRecord.Name+'-'+System.now().getTime();
            HttpResponse responseInstance = getRealTimeEgiftBulk(getBlackhawkEGiftRequestWInputWrapper(memberBenefitRecord));
            String statusCode = String.valueOf(responseInstance.getStatusCode());
            if(statusCode == SUCCESSCODE){
                RealTimeEgiftBulkSuccessWrapper successWrap = new RealTimeEgiftBulkSuccessWrapper();
                rtebrWrap = new RealTimeEgiftBulkResponseWrapper(false,statusCode,successWrap.parse(responseInstance.getBody()),null);
                System.debug('success >>> '+rtebrWrap);
            }
            else if(statusCode.startsWith('4') || statusCode.startsWith('5')){
                RealTimeEgiftBulkErrorWrapper errorWrap = new RealTimeEgiftBulkErrorWrapper();
                rtebrWrap = new RealTimeEgiftBulkResponseWrapper(true,statusCode,new RealTimeEgiftBulkSuccessWrapper(),errorWrap.parse(responseInstance.getBody()));
                System.debug('error >>> '+rtebrWrap);
                if(memberBenefitRecord.Gift_Card_Request_Counter__c == 0) throw new BlackhawkApiServiceException('Status Code: '+rtebrWrap.statusCode + ' - ' + JSON.serialize(rtebrWrap.errorWrap));
            }
        }
        catch(Exception e){
            logger.Module('Integration')
                    .ExceptionCause('ApiError')
                    .SourceObject('Member_Benefit__c')
                    .SourceRecord(memberBenefitRecord.Id)
                    .log(e);
        }
        return rtebrWrap;
    }

    public static RealTimeEgiftBulkResponseWrapper getEGiftBulkCodeRetrievalInfo(Member_Benefit__c memberBenefitRec){
        
        HttpResponse responseInstance = BlackhawkAPIService.getEGiftBulkCodeRetrieval(memberBenefitRec);
        String statusCode = String.valueOf(responseInstance.getStatusCode());
        RealTimeEgiftBulkResponseWrapper rtebrWrap;

        if(statusCode == '200'){
            rtebrWrap = new RealTimeEgiftBulkResponseWrapper(false,statusCode,BlackhawkEGiftWrapper.parse(responseInstance.getBody()),null);
        }
        else if(statusCode == '400'){
            RealTimeEgiftBulkErrorWrapper errorWrap = new RealTimeEgiftBulkErrorWrapper();
            rtebrWrap = new RealTimeEgiftBulkResponseWrapper(true,statusCode,new RealTimeEgiftBulkSuccessWrapper(),errorWrap.parse(responseInstance.getBody()));
        }
        return rtebrWrap;

    }

    public static HttpResponse monitorRewards(){
        Blackhawk_API_Settings__c bhAPISetting = getActiveBlackhawkApiSetting();
        Http httpInstance = new Http();
        HttpRequest httpRequestInstance = new HttpRequest();
        httpRequestInstance.setEndpoint(bhAPISetting.Monitoring_Status_Endpoint__c);
        httpRequestInstance.setClientCertificateName(bhAPISetting.Client_Certificate_Name__c);
        httpRequestInstance.setHeader('Content-Type','application/json');
        httpRequestInstance.setHeader('Merchantid',bhAPISetting.Merchant_Id__c);
        httpRequestInstance.setHeader('Requestid',String.valueOf(DateTime.now().millisecond()));
        httpRequestInstance.setMethod('GET');
        HttpResponse httpResponse = httpInstance.send(httpRequestInstance);  
        System.debug('Request >>> ');
        System.debug('Current Date Time = ' + System.Now().format());
        System.debug('Endpoint = ' + httpRequestInstance.getEndpoint());
        System.debug('Header Content-Type = ' + httpRequestInstance.getHeader('Content-Type'));
        System.debug('Header Merchantid = ' + httpRequestInstance.getHeader('Merchantid'));
        System.debug('Header Requestid = ' + httpRequestInstance.getHeader('Requestid'));
        System.debug('Request Body = ' + httpRequestInstance.getBody());
        System.debug('Response Body = ' + httpResponse.getBody());
        return httpResponse;        
    }

    public static HttpResponse getCatalogByKey(String clientProgramId){
        Blackhawk_API_Settings__c bhAPISetting = getActiveBlackhawkApiSetting();
        Http httpInstance = new Http();
        HttpRequest httpRequestInstance = new HttpRequest();
        httpRequestInstance.setEndpoint(bhAPISetting.Catalog_API_Endpoint__c+'?clientProgramId='+clientProgramId);
        httpRequestInstance.setClientCertificateName(bhAPISetting.Client_Certificate_Name__c);
        httpRequestInstance.setHeader('Content-Type','application/json');
        httpRequestInstance.setHeader('Merchantid',bhAPISetting.Merchant_Id__c);
        httpRequestInstance.setHeader('Requestid',String.valueOf(System.now().getTime())); 
        httpRequestInstance.setMethod('GET');
        HttpResponse httpResponse = httpInstance.send(httpRequestInstance);  
        System.debug('Request >>> ');
        System.debug('Current Date Time = ' + System.Now().format());
        System.debug('Endpoint = ' + httpRequestInstance.getEndpoint());
        System.debug('Header Content-Type = ' + httpRequestInstance.getHeader('Content-Type'));
        System.debug('Header Merchantid = ' + httpRequestInstance.getHeader('Merchantid'));
        System.debug('Header Requestid = ' + httpRequestInstance.getHeader('Requestid'));
        System.debug('Request Body = ' + httpRequestInstance.getBody());
        System.debug('Response Body = ' + httpResponse.getBody());
        return httpResponse;
    }

    public static HttpResponse getRealTimeEgiftBulk(BlackhawkEGiftRequestWInputWrapper requestWrap){
        Blackhawk_API_Settings__c bhAPISetting = getActiveBlackhawkApiSetting();
        Http httpInstance = new Http();
        HttpRequest httpRequestInstance = new HttpRequest();
        httpRequestInstance.setTimeout(120000);
        httpRequestInstance.setEndpoint(bhAPISetting.Real_time_eGift_Endpoint__c);
        httpRequestInstance.setClientCertificateName(bhAPISetting.Client_Certificate_Name__c);
        httpRequestInstance.setHeader('Content-Type','application/json');
        httpRequestInstance.setHeader('Merchantid',bhAPISetting.Merchant_Id__c);
        httpRequestInstance.setHeader('Requestid',requestWrap.requestId);
        httpRequestInstance.setHeader('millisecondsToWait',bhAPISetting.Milliseconds_To_Wait__c);
        httpRequestInstance.setHeader('SYNCHRONOUS_ONLY',String.valueOf(bhAPISetting.SYNCHRONOUS_ONLY__c));
        httpRequestInstance.setMethod('POST');
        httpRequestInstance.setBody(generateRequest(requestWrap,bhAPISetting));  
        HttpResponse httpResponse = httpInstance.send(httpRequestInstance); 
        System.debug('Request >>> ');
        System.debug('Current Date Time = ' + System.Now().format());
        System.debug('Endpoint = ' + httpRequestInstance.getEndpoint());
        System.debug('Header Content-Type = ' + httpRequestInstance.getHeader('Content-Type'));
        System.debug('Header Merchantid = ' + httpRequestInstance.getHeader('Merchantid'));
        System.debug('Header Requestid = ' + httpRequestInstance.getHeader('Requestid'));
        System.debug('Header millisecondsToWait = ' + httpRequestInstance.getHeader('millisecondsToWait'));
        System.debug('Header SYNCHRONOUS_ONLY = ' + httpRequestInstance.getHeader('SYNCHRONOUS_ONLY'));
        System.debug('Request Body = ' + httpRequestInstance.getBody());
        System.debug('Response Body = ' + httpResponse.getBody());
        return httpResponse; 
    }

    public static HttpResponse getEGiftBulkCodeRetrieval(Member_Benefit__c memberBenefitRecord){
        Blackhawk_API_Settings__c bhAPISetting = getActiveBlackhawkApiSetting();
        Http httpInstance = new Http();
        HttpRequest httpRequestInstance = new HttpRequest();
        httpRequestInstance.setTimeout(120000);
        httpRequestInstance.setEndpoint(bhAPISetting.eGift_Bulk_Code_Retrieval_Endpoint__c+'?requestId='+memberBenefitRecord.Request_Id__c+'&clientProgramNumber='+bhAPISetting.Client_Program_Id__c);
        httpRequestInstance.setClientCertificateName(bhAPISetting.Client_Certificate_Name__c);
        httpRequestInstance.setHeader('Content-Type','application/json');
        httpRequestInstance.setHeader('Merchantid',bhAPISetting.Merchant_Id__c);
        httpRequestInstance.setHeader('Requestid',memberBenefitRecord.Request_Id__c);
        httpRequestInstance.setHeader('millisecondsToWait',bhAPISetting.Milliseconds_To_Wait__c);
        httpRequestInstance.setHeader('SYNCHRONOUS_ONLY',String.valueOf(bhAPISetting.SYNCHRONOUS_ONLY__c));
        httpRequestInstance.setMethod('GET');
        HttpResponse httpResponse = httpInstance.send(httpRequestInstance); 
        String statusCode = String.valueOf(httpResponse.getStatusCode());
        // System.debug(statusCode);
        // System.debug(httpResponse.getBody());
        System.debug('Request >>> ');
        System.debug('Current Date Time = ' + System.Now().format());
        System.debug('Endpoint = ' + httpRequestInstance.getEndpoint());
        System.debug('Header Content-Type = ' + httpRequestInstance.getHeader('Content-Type'));
        System.debug('Header Merchantid = ' + httpRequestInstance.getHeader('Merchantid'));
        System.debug('Header Requestid = ' + httpRequestInstance.getHeader('Requestid'));
        System.debug('Header millisecondsToWait = ' + httpRequestInstance.getHeader('millisecondsToWait'));
        System.debug('Header SYNCHRONOUS_ONLY = ' + httpRequestInstance.getHeader('SYNCHRONOUS_ONLY'));
        System.debug('Request Body = ' + httpRequestInstance.getBody());
        System.debug('Response Body = ' + httpResponse.getBody());
        if(statusCode == '200'){
            RealTimeEgiftBulkResponseWrapper rtebrWrap;
            rtebrWrap = new RealTimeEgiftBulkResponseWrapper(false,statusCode,BlackhawkEGiftWrapper.parse(httpResponse.getBody()),null);
            System.debug(rtebrWrap);
        }
        return httpResponse; 
    }

    public static BlackhawkEGiftRequestWInputWrapper getBlackhawkEGiftRequestWInputWrapper(Member_Benefit__c memberBenefitRecord){
        String counter = (memberBenefitRecord.Gift_Card_Request_Counter__c != NULL) ? String.valueOf(memberBenefitRecord.Gift_Card_Request_Counter__c) : '0';
        return new BlackhawkEGiftRequestWInputWrapper(memberBenefitRecord.Request_Id__c, memberBenefitRecord.Name+'-'+counter, memberBenefitRecord.Member_Benefit_Program__r.Gift_Card_Value__c, memberBenefitRecord.Member_Benefit_Program__r.Blackhawk_Catalog_Lookup__r.Content_Provider_Code__c); 
    }

    public static List<Blackhawk_Card_Product__c> generateBlackhawkCardProducts (BlackhawkClientProgramWrapper blackhawkClientWrapObj){

        List<Blackhawk_Card_Product__c> blackHawkCardProductListToInsert = new List<Blackhawk_Card_Product__c>();

        if(blackhawkClientWrapObj.products.size() > 0){
            for(BlackhawkClientProgramWrapper.Products product : blackhawkClientWrapObj.products){
                Blackhawk_Card_Product__c bcp = new Blackhawk_Card_Product__c();
                bcp.Name = product.contentProviderCode;
                bcp.Client_Program_Id__c = blackhawkClientWrapObj.clientProgramId;
                bcp.Content_Provider_Code__c = product.contentProviderCode;
                bcp.Currency__c = blackhawkClientWrapObj.currency_Z;
                bcp.Locale__c = product.locale;
                bcp.Logo_Image__c = product.logoImage;
                bcp.VR_Maximum__c = product.valueRestrictions.maximum;
                bcp.VR_Minimum__c = product.valueRestrictions.minimum;
                bcp.Parent_Brand_Name__c = product.parentBrandName;
                bcp.Product_Description__c = product.productDescription;
                bcp.Product_Image__c = product.productImage;
                bcp.Product_Name__c = product.productName;
                bcp.Program_Name__c = blackhawkClientWrapObj.programName;
                bcp.Program_Type__c = blackhawkClientWrapObj.programType;
                bcp.Redemption_Info__c = blackhawkClientWrapObj.programType;
                bcp.TNC_Text__c = product.termsAndConditions.text;
                bcp.TNC_Type__c = product.termsAndConditions.type;
                blackHawkCardProductListToInsert.add(bcp);
            }
        }
        
        return blackHawkCardProductListToInsert;
    }

    private static String generateRequest(BlackhawkEGiftRequestWInputWrapper requestWrap, Blackhawk_API_Settings__c bhAPISetting){
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('clientProgramNumber', bhAPISetting.Client_Program_Id__c);
        gen.writeStringField('paymentType', bhAPISetting.Payment_Type__c);
        gen.writeStringField('returnCardNumberAndPIN', String.valueOf(bhAPISetting.Return_Card_Number_and_PIN__c));
        gen.writeFieldName('orderDetails');
        gen.writeStartArray();
        gen.writeStartObject();
        gen.writeStringField('clientRefId', requestWrap.clientReferenceId);
        gen.writeStringField('quantity', '1');
        gen.writeStringField('amount', String.valueOf(requestWrap.amount));
        gen.writeStringField('contentProvider', requestWrap.contentProvider);
        gen.writeEndObject();
        gen.writeEndArray();
        gen.writeEndObject();
        String pretty = gen.getAsString();
        return pretty;
    }

    public class RealTimeEgiftBulkResponseWrapper{

        public Boolean hasError {get;set;}
        public String statusCode {get;set;}
        public RealTimeEgiftBulkSuccessWrapper successWrap {get;set;}
        public RealTimeEgiftBulkErrorWrapper errorWrap {get;set;}
        public BlackhawkEGiftWrapper successEGiftWrap {get;set;}

        public RealTimeEgiftBulkResponseWrapper (Boolean hasError, String statusCode, RealTimeEgiftBulkSuccessWrapper successWrap, RealTimeEgiftBulkErrorWrapper errorWrap){
            this.hasError = hasError;
            this.statusCode = statusCode;
            this.successWrap = successWrap;
            this.errorWrap = errorWrap;
        } 

        public RealTimeEgiftBulkResponseWrapper (Boolean hasError, String statusCode, BlackhawkEGiftWrapper successEGiftWrap, RealTimeEgiftBulkErrorWrapper errorWrap){
            this.hasError = hasError;
            this.statusCode = statusCode;
            this.successEGiftWrap = successEGiftWrap;
            this.errorWrap = errorWrap;
        } 

    }

    public class RealTimeEgiftBulkSuccessWrapper{

        public String transactionId;	
        public Boolean isCompleted;
        public Integer percentComplete;	
        public boolean success;
        public String orderNumber;
        public String url;	
        public String contentProviderCode;	
        public Decimal transactionAmount;

        public RealTimeEgiftBulkSuccessWrapper parse(String json){
            return (RealTimeEgiftBulkSuccessWrapper) System.JSON.deserialize(json, RealTimeEgiftBulkSuccessWrapper.class);
        }
    
    }

    public class RealTimeEgiftBulkErrorWrapper {

        public List<Errors> errors;
    
        public RealTimeEgiftBulkErrorWrapper parse(String json) {
            return (RealTimeEgiftBulkErrorWrapper) System.JSON.deserialize(json, RealTimeEgiftBulkErrorWrapper.class);
        }
    }

    public class Errors {
        public String errorCode;
        public String message;
    }

    public class BlackhawkEGiftRequestWInputWrapper{

        public String requestId {get;set;} 
        public String clientReferenceId {get;set;} 
        public Decimal amount {get;set;} 
        public String contentProvider {get;set;} 
        
        public BlackhawkEGiftRequestWInputWrapper (String requestId, String clientReferenceId, Decimal amount, String contentProvider){
            this.requestId = requestId;
            this.clientReferenceId = clientReferenceId;
            this.amount = amount;
            this.contentProvider = contentProvider;
        }

    }

    public static Blackhawk_API_Settings__c getActiveBlackhawkApiSetting (){
        return [SELECT  Id, Catalog_API_Endpoint__c, Client_Program_Id__c, Is_Active__c, Merchant_Id__c, 
                        Milliseconds_To_Wait__c, Monitoring_Status_Endpoint__c, Payment_Type__c, Real_time_eGift_Endpoint__c,
                        Return_Card_Number_and_PIN__c, SYNCHRONOUS_ONLY__c, Client_Certificate_Name__c, Maximum_Retry_Count__c,
                        eGift_Bulk_Code_Retrieval_Endpoint__c
                FROM Blackhawk_API_Settings__c
                WHERE Is_Active__c = TRUE];
    }

}