force-app/main/default/objects/Blackhawk_API_Settings__c/Blackhawk_API_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Blackhawk API Settings</label>
</CustomObject>

force-app/main/default/objects/Blackhawk_API_Settings__c/fields/Maximum_Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Retry_Count__c</fullName>
    <label>Maximum Retry Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Blackhawk_Card_Product__c/Blackhawk_Card_Product__c.object-meta.xml
<CustomObject>
    <description>The Hawk Marketplace Rewards Catalog Processing API allows you to access the catalog of card products that have been made available for you to order.

The card catalog is specifically configured to your sub-organization and client programs in the Hawk Marketplace platform. It is not a global catalog of all products available from Blackhawk Network. If you do not see a product you believe should be available for you to order, or you would like to add a new product to your catalog, reach out to your Account Manager.</description>
    <label>Blackhawk Catalog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blackhawk Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Blackhawk_Card_Product__c/fields/Content_Provider_Code__c.field-meta.xml
<CustomField>
    <fullName>Content_Provider_Code__c</fullName>
    <externalId>true</externalId>
    <label>Content Provider Code</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Member_Benefit__c/Member_Benefit__c.object-meta.xml
<CustomObject>
    <label>Member Benefit</label>
    <nameField>
        <displayFormat>MB-{00000}</displayFormat>
        <label>Member Benefit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit__c/fields/Gift_Card_Provider_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Gift_Card_Provider_Error_Message__c</fullName>
    <label>Error Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Member_Benefit__c/fields/Gift_Card_Request_Counter__c.field-meta.xml
<CustomField>
    <fullName>Gift_Card_Request_Counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Request Counter</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member_Benefit__c/fields/Member_Benefit_Program__c.field-meta.xml
<CustomField>
    <fullName>Member_Benefit_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Benefit Program</label>
    <referenceTo>Member_Benefit_Program__c</referenceTo>
    <relationshipLabel>Member Benefits</relationshipLabel>
    <relationshipName>Member_Benefits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Further Information Required</fullName>
            </value>
            <value>
                <fullName>Approved - Awaiting Activation</fullName>
            </value>
            <value>
                <fullName>Approved - Activated</fullName>
            </value>
            <value>
                <fullName>Approved - Gift Card Platform Success</fullName>
            </value>
            <value>
                <fullName>Approved - Gift Card Platform Error</fullName>
            </value>
            <value>
                <fullName>Approved - Gift Card Issued</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/Member_Benefit_Program__c.object-meta.xml
<CustomObject>
    <label>Member Benefit Program</label>
    <nameField>
        <label>Member Benefit Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Benefit Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Blackhawk_Catalog_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Blackhawk_Catalog_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Blackhawk Catalog</label>
    <referenceTo>Blackhawk_Card_Product__c</referenceTo>
    <relationshipLabel>Member Benefit Programs</relationshipLabel>
    <relationshipName>Member_Benefit_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Gift_Card_Value__c.field-meta.xml
<CustomField>
    <fullName>Gift_Card_Value__c</fullName>
    <label>Gift Card Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BlackhawkAPIBatch.cls
/**
* @author: Rexie Aaron David
* @date: October 2023
* @description: Batch Class to invoke Blackhawk API
*/ 
global class BlackhawkAPIBatch implements database.Batchable<sObject>,Database.AllowsCallouts,Database.Stateful {

    public List<Member_Benefit__c> memberBenefitListToProcess = new List<Member_Benefit__c>();
    public List<Member_Benefit__c> memberBenefitToUpdateList = new List<Member_Benefit__c>();
    public String integAction = '';
    public static final String APPROVEDGIFTCARDSUCCESS = 'Approved - Gift Card Platform Success';
    public static final String APPROVEDGIFTCARDERROR = 'Approved - Gift Card Platform Error';
    public static final String CURRENTLYUNAVAILABLE = 'The service is not currently available';
    public static final String ORDERISCANCELLED = 'Order is cancelled due to failure to meet SLA for this SYNCHRONOUS_ONLY order';
    public static final String REQUESTCANNOTBEPROCESSED = 'Request cannot be processed at this time';
    public static final String ORDERNOTSUBMITTED = 'An error has occurred and your order has not been submitted';
    public static final String NOPERMISSION = 'Does not have permissions to submit order using this quote';
    
    public Blackhawk_API_Settings__c blackhawkApiSetting = new Blackhawk_API_Settings__c();
    public String query = 'SELECT Id, Name, Gift_Card_Request_Counter__c, Gift_Card_Provider_Error_Message__c, Member_Benefit_Program__r.Blackhawk_Catalog_Lookup__c, Member_Benefit_Program__c, Member_Benefit_Program__r.Gift_Card_Value__c, Member_Benefit_Program__r.Blackhawk_Catalog_Lookup__r.Content_Provider_Code__c FROM Member_Benefit__c ';

    global BlackhawkAPIBatch(String action, List<Member_Benefit__c> memberBenefitList) {
        integAction = action;
        memberBenefitListToProcess = memberBenefitList;
        if(blackhawkApiSetting.Id == NULL) blackhawkApiSetting = BlackhawkAPIService.getActiveBlackhawkApiSetting();
    }

    global Database.querylocator start(Database.BatchableContext BC){
        
        Integer maxRetry = Integer.valueOf(blackhawkApiSetting.Maximum_Retry_Count__c);
        if(integAction == 'submit') query += ' WHERE Id IN: memberBenefitListToProcess';
        else if(integAction == 'retry') query += ' WHERE Id IN: memberBenefitListToProcess AND Status__c =: APPROVEDGIFTCARDERROR AND Gift_Card_Request_Counter__c != 0 AND Gift_Card_Request_Counter__c != NULL AND Gift_Card_Request_Counter__c <: maxRetry';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        List<Member_Benefit__c> memberBenefitList = (List<Member_Benefit__c>)scope;
        MembershipLoyaltyController.WithoutShare membershipControllerElevContext = new MembershipLoyaltyController.WithoutShare();

        for(Member_Benefit__c memberBenefit : memberBenefitList){
            if(LIMITS.getCallouts() < LIMITS.getLimitCallouts()){
                if(integAction == 'submit' && memberBenefit.Member_Benefit_Program__r.Gift_Card_Value__c != NULL && memberBenefit.Member_Benefit_Program__r.Blackhawk_Catalog_Lookup__c != NULL){
                    memberBenefit = membershipControllerElevContext.updateMemberBenefitFields(memberBenefit,  BlackhawkAPIService.submitRealTimeEgiftBulk(memberBenefit));
                    memberBenefitToUpdateList.add(memberBenefit);
                }
                if(integAction == 'retry' && memberBenefit.Gift_Card_Provider_Error_Message__c.containsIgnoreCase(BlackhawkAPIService.RETRYSTATUSCODE)){
                    memberBenefit = membershipControllerElevContext.updateMemberBenefitFields(memberBenefit,  BlackhawkAPIService.submitRealTimeEgiftBulk(memberBenefit));
                    memberBenefitToUpdateList.add(memberBenefit);
                }
            }
        }
    }

    global void finish(Database.BatchableContext BC){
        if(!memberBenefitToUpdateList.isEmpty()){
            try{
                update memberBenefitToUpdateList;
            }
            catch (Exception ex){
                System.debug('BlackhawkAPIBatch >>> finish >>> '+ex.getMessage());
            }    
        }
    }

}