force-app/main/default/objects/TTI_Error_Log__c/TTI_Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TTI_Error_Log__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TTI_Error_Log__c/fields/TTI_Cause__c.field-meta.xml
<CustomField>
    <fullName>TTI_Cause__c</fullName>
    <label>Cause</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TTI_Error_Log__c/fields/TTI_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>TTI_Line_Number__c</fullName>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TTI_Error_Log__c/fields/TTI_Message__c.field-meta.xml
<CustomField>
    <fullName>TTI_Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TTI_Error_Log__c/fields/TTI_Stack_Trace_String__c.field-meta.xml
<CustomField>
    <fullName>TTI_Stack_Trace_String__c</fullName>
    <label>Stack Trace String</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TTI_Error_Log__c/fields/TTI_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>TTI_Type_Name__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogException.cls
/**
* @author: Rexie Aaron David
* @date: October 2023
* @description: This class handles LogException 
* @reference: https://salesforceable.medium.com/a-handy-error-logger-in-salesforce-to-write-the-exceptions-to-a-custom-object-2b6f79e4c0ef
*/ 
public class LogException extends Exception {

    public String ModuleName {get; set;}
    public String StackTrace {get; set;}
    public String ClassName {get; set;}
    public String MethodName {get; set;}
    public String ExceptionCause {get; set;}
    public String SourceObject {get; set;}
    public String SourceRecord {get; set;}
        
    public void log(Exception ex){
        try{
            extractExceptionData(ex); 
            writeToObject(ex);
        }
        catch(Exception e){
            new LogException().Module('LogException').log(e);            
        }                 
    }
    
    public LogException Module(String Name){
        ModuleName = name;
        return this;
    }
    
    public LogException ExceptionCause(String cause){
        ExceptionCause = cause;
        return this;
    }

    public LogException SourceObject(String sourceObj){
        SourceObject = sourceObj;
        return this;
    }

    public LogException SourceRecord(String recordId){
        SourceRecord = recordId;
        return this;
    }


    
    public void extractExceptionData(Exception ex){
        try{
            stackTrace = ex.getStackTraceString()
                         .substringBefore('\n');
            
            className = stackTrace.substringAfter('.')
                        .substringBefore('.'); 
            
            methodName = stackTrace.substringBefore(':')
                         .substringAfter(className)
                         .substringAfter('.');    
        }
        catch(Exception e){
            new LogException().Module('LogException').log(e); 
        }                      
    }
    
    public void writeToObject(Exception ex){
        try{
            TTI_Error_Log__c logger = new TTI_Error_Log__c();
            logger.Module_Name__c = ModuleName;
            logger.TTI_Stack_Trace_String__c = ex.getStackTraceString();
            logger.Class_Name__c = className;
            logger.Method_Name__c = methodName;
            logger.TTI_Line_Number__c = ex.getLineNumber();
            logger.TTI_Type_Name__c = ex.getTypeName();
            logger.Exception_Cause_Override__c = ExceptionCause; 
            logger.TTI_Cause__c = String.valueOf(ex.getCause());
            logger.TTI_Message__c = ex.getMessage();
            logger.Source_Object__c = SourceObject;
            logger.Source_Record_ID__c = SourceRecord;
            insert logger;    
        }
        catch(Exception e){
            new LogException().Module('LogException').log(e);     
        }
        
    }
    
}