force-app/main/default/objects/TTI_Error_Log__c/TTI_Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TTI_Error_Log__c/fields/TTI_Cause__c.field-meta.xml
<CustomField>
    <fullName>TTI_Cause__c</fullName>
    <label>Cause</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TTI_Error_Log__c/fields/TTI_Input_Parameters__c.field-meta.xml
<CustomField>
    <fullName>TTI_Input_Parameters__c</fullName>
    <label>Input Parameters</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TTI_Error_Log__c/fields/TTI_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>TTI_Line_Number__c</fullName>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TTI_Error_Log__c/fields/TTI_Message__c.field-meta.xml
<CustomField>
    <fullName>TTI_Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TTI_Error_Log__c/fields/TTI_Stack_Trace_String__c.field-meta.xml
<CustomField>
    <fullName>TTI_Stack_Trace_String__c</fullName>
    <label>Stack Trace String</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TTI_Error_Log__c/fields/TTI_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>TTI_Type_Name__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TTI_LogError.cls
public class TTI_LogError {
    public static void createExceptionLog(Exception exceptionCaught, String inputParamJason){
        TTI_Error_Log__c objException = new TTI_Error_Log__c();
        objException.TTI_Cause__c = String.valueOf(exceptionCaught.getCause());
        objException.TTI_Line_Number__c = exceptionCaught.getLineNumber();
        objException.TTI_Message__c = exceptionCaught.getMessage();
        objException.TTI_Stack_Trace_String__c = exceptionCaught.getStackTraceString();
        objException.TTI_Type_Name__c = exceptionCaught.getTypeName();
        objException.TTI_Input_Parameters__c = inputParamJason;
        insert objException;
    }
}