force-app/main/default/objects/Asset/fields/Member_Benefit__c.field-meta.xml
<CustomField>
    <fullName>Member_Benefit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Benefit</label>
    <referenceTo>Member_Benefit__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eligible_Customer__c/Eligible_Customer__c.object-meta.xml
<CustomObject>
    <description>Member Benefit Program: Eligible Customers - Junction Object to link Account and Member Benefit Program</description>
    <label>Eligible Customer</label>
    <nameField>
        <displayFormat>ECN-{00000}</displayFormat>
        <label>Eligible Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligible Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eligible_Customer__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eligible Campaigns</relationshipLabel>
    <relationshipName>Eligible_Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eligible_Customer__c/fields/Customer_ContactId__c.field-meta.xml
<CustomField>
    <fullName>Customer_ContactId__c</fullName>
    <formula>CASESAFEID(Customer__r.PersonContact.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer ContactId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eligible_Customer__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Customer__r.PersonContact.FirstName +&apos; &apos;+ Customer__r.PersonContact.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eligible_Customer__c/fields/Member_Benefit_Program__c.field-meta.xml
<CustomField>
    <fullName>Member_Benefit_Program__c</fullName>
    <label>Member Benefit Program</label>
    <referenceTo>Member_Benefit_Program__c</referenceTo>
    <relationshipLabel>Eligible Customers</relationshipLabel>
    <relationshipName>Eligible_Customers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eligible_Product_Line_Item__c/Eligible_Product_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Eligible Product Line Item</label>
    <nameField>
        <displayFormat>EPPLI-{000000}</displayFormat>
        <label>Eligible Product Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligible Product Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eligible_Product_Line_Item__c/fields/Customer_Facing_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Facing_Name__c</fullName>
    <formula>Product__r.Customer_Facing_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Facing Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eligible_Product_Line_Item__c/fields/Eligible_Product__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Product__c</fullName>
    <label>Eligible Product</label>
    <referenceTo>Eligible_Products__c</referenceTo>
    <relationshipLabel>Eligible Product Line Items</relationshipLabel>
    <relationshipName>Eligible_Product_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eligible_Product_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eligible Product Line Items</relationshipLabel>
    <relationshipName>Eligible_Product_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eligible_Product_Line_Item__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <formula>Product__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Model</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eligible_Products__c/Eligible_Products__c.object-meta.xml
<CustomObject>
    <label>Eligible Products</label>
    <nameField>
        <displayFormat>EP-{000000}</displayFormat>
        <label>Eligible Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligible Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit__c/Member_Benefit__c.object-meta.xml
<CustomObject>
    <label>Member Benefit</label>
    <nameField>
        <displayFormat>MB-{00000}</displayFormat>
        <label>Member Benefit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Member Benefits</relationshipLabel>
    <relationshipName>Member_Benefits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit__c/fields/Member_Benefit_Program__c.field-meta.xml
<CustomField>
    <fullName>Member_Benefit_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Benefit Program</label>
    <referenceTo>Member_Benefit_Program__c</referenceTo>
    <relationshipLabel>Member Benefits</relationshipLabel>
    <relationshipName>Member_Benefits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/Member_Benefit_Program__c.object-meta.xml
<CustomObject>
    <label>Member Benefit Program</label>
    <nameField>
        <label>Member Benefit Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Benefit Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Eligible_Products__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eligible Products</label>
    <referenceTo>Eligible_Products__c</referenceTo>
    <relationshipLabel>Member Benefit Programs</relationshipLabel>
    <relationshipName>Member_Benefit_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Purchase End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Product_Hierarchies__c.field-meta.xml
<CustomField>
    <fullName>Product_Hierarchies__c</fullName>
    <label>Product Hierarchies</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Purchase Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Valid_From__c</fullName>
    <label>Registration Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Valid_To__c.field-meta.xml
<CustomField>
    <fullName>Valid_To__c</fullName>
    <label>Registration End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Untitled-1.cls
/** 
 * @description:        Controller Membership Loyalty Program Automations
 * 
 * @author:             Rexie David
 * @date:               10/3/2023
*/
public with sharing class MembershipLoyaltyContoller {
    
    public WithoutShare withoutSharing = new WithoutShare();
    
    public static List<Member_Benefit__c> generateMemberBenefits (Set<String> assetIds){

        List<Member_Benefit__c> memberBenefitToInsertList = new List<Member_Benefit__c>();

        List<Asset> registeredProductList = withoutSharing.getAssets(assetIds); // Retrieve Assets (Registered Products)

        Set<String> assetCustomerAccountIds = new Set<String>();
        Set<String> productCodes = new Set<String>();
        Set<String> productHierarchies = new Set<String>();
        Set<String> eligibleProductIds = new Set<String>();

        Map<String,List<Asset>> customerAssetListMap = new Map<String,List<Asset>>(); //Map of Key: Customer(PersonAccountId) - Value: List of Asset
        //Map<String,List<Eligible_Customer__c>> campaignEligibleCustomerListMap = new Map<String,List<Eligible_Customer__c>>();
        Map<String,List<Asset>> campaignAssetListMap = new Map<String,List<Asset>>(); //Map of Key: Campaign (Member_Benefit_Program__c) - Value: List of Asset

        // Map<String,List<Eligible_Product_Line_c> campaignEligibleProductMap = new Map<String,Eligible_Product_Line_c>();

        //Loop through Registered Products
        for(Asset assetRecord : registeredProductList){
            if(assetRecord.AccountId) assetCustomerAccountIds.add(assetRecord.AccountId);
            if(assetRecord.ProductCode) productCodeIds.add(assetRecord.ProductCode);
            if(assetRecord.SAPProductHeirarchy__c) productHierarchies.add(assetRecord.SAPProductHeirarchy__c);

            // //Populate Customer(PersonAccountId) - List of Asset
            // if(customerAssetListMap.containsKey(assetRecord.AccountId)){
            //     customerAssetListMap.put(assetRecord.AccountId,customerAssetListMap.get(assetRecord.AccountId).add(assetRecord));
            // }
            // else{
            //     customerAssetListMap.put(assetRecord.AccountId,new List<Asset>{asset});
            // }
        }
        
       




        if(assetCustomerAccountIds.size() > 0){
            //Loop through the Eligible_Customer__c records
            List<Eligible_Customer__c> eligibleCustomerList = withoutSharing.getEligibleCustomers(assetCustomerAccountIds);

            for(Eligible_Customer__c eligibleCustomer : eligibleCustomerList){

                if(customerAssetListMap.containsKey(eligibleCustomer.Customer__c)){

                    for(Asset assetRecord : customerAssetListMap.get(eligibleCustomer.Customer__c)){
                    
                        if(meetsDateRange(assetRecord,eligibleCustomer)){
                            //We have confirmed the assetRecord DATE eligibility based on the Eligible_Customer__c records, 
                            //next we have to confirm the assetRecord PRODUCT/PRODUCTHIERARCHY eligibility based on the Eligible Product
                            System.debug(eligibleCustomer.Customer_Name__c + ' is Eligible for ' + eligibleCustomer.Member_Benefit_Program__r.Name 
                            + ' by Purchasing '+assetRecord.ProductCode+' - '+assetRecord.ProductDescription + ' last ' +assetRecord.PurchaseDate + ' and Registered it on ' +regDate 
                            +'. Campaign Purchase Period starts at '+eligibleCustomer.Member_Benefit_Program__r.Start_Date__c + ' until ' +eligibleCustomer.Member_Benefit_Program__r.End_Date__c 
                            +' and Registration Period starts at '+eligibleCustomer.Member_Benefit_Program__r.Valid_From__c + ' until ' + eligibleCustomer.Member_Benefit_Program__r.Valid_To__c);
                            eligibleProductIds.add(eligibleCustomer.Member_Benefit_Program__r.Eligible_Products__c);
                            productCodes.add(assetRecord.ProductCode);
                            productHierarchies.add(assetRecord.SAPProductHeirarchy__c);

                            if(campaignAssetListMap.containsKey(eligibleCustomer.Member_Benefit_Program__c)){
                                //Map Key: Campaign (Member_Benefit_Program__c), Value: List<Eligible_Customer__c>
                                campaignAssetListMap.put(eligibleCustomer.Member_Benefit_Program__c,campaignAssetListMap.get(eligibleCustomer.Member_Benefit_Program__c).add(assetRecord));
                            }
                            else{
                                campaignAssetListMap.put(eligibleCustomer.Member_Benefit_Program__c,new List<Asset> {assetRecord});
                            }
                        }
                    }
                }
            }    

            for(Eligible_Product__c eligibleProduct : withoutSharing.getEligibleProducts(eligibleProductIds,productCodes,campaignAssetListMap.keySet())){
                campaignEligibleProductMap.put(eligibleProduct.);
            }

            //Loop through the Initial Eligible campaignAssetListMap
            for(String campaignId : campaignAssetListMap.keySet()){
                if(campaignAssetListMap.containsKey(campaignId)){
                    for(Asset assetRecord : campaignAssetListMap.get(campaignId)){

                    }

                }
            }

            //Query Eligible Product 
            //Map of Key: Campaign (Member_Benefit_Program__c) - Value: List of Eligible_Product_Line_Item__c
            //Map<String, List<Eligible_Product_Line_Item__c>> campaignEligibleProductLineItemListMap = new  Map<String, List<Eligible_Product_Line_Item__c>>();

        }
        
        System.debug('assetCustomerAccountIds >>> '+assetCustomerAccountIds);
        System.debug('productCodes >>> '+productCodes);
        System.debug('productHierarchies >>> '+productHierarchies);
        System.debug('eligibleProductIds >>> '+eligibleProductIds);

        //List<Member_Benefit_Program__c> memberBenefitProgramList = withoutSharing.getMemberBenefitPrograms(new List<String> {'Ryobi'});

        Boolean isEligible = false;

        try{

        }

        catch(Exception e){

        }

        return isEligible;

    }

    private static Boolean meetsDateRange(Asset assetRecord, Eligible_Customer__c eligibleCustomer){

        Boolean meetsDateRange = false;
        DateTime regDateTime = assetRecord.Registered_Date_Formula__c;
        Date regDate = date.newinstance(regDateTime.year(), regDateTime.month(), regDateTime.day());
        if(assetRecord.PurchaseDate >= eligibleCustomer.Member_Benefit_Program__r.Start_Date__c 
        && assetRecord.PurchaseDate <= eligibleCustomer.Member_Benefit_Program__r.End_Date__c
        && regDate >= eligibleCustomer.Member_Benefit_Program__r.Valid_From__c
        && regDate <= eligibleCustomer.Member_Benefit_Program__r.Valid_To__c){
            meetsDateRange = true;
        }
        return meetsDateRange;
    } 

    public class EligibleCustomer {

        public Member_Benefit_Program__c campaign {get; set;}
        public Asset asset {get; set;}

        public EligibleCustomer (Asset asset){
            this.asset = asset;
        }   

    }
    
    public without sharing class WithoutShare {

        public List<Eligible_Products__c> getEligibleProducts(Set<String> eligibleProductIds, Set<String> productCodes, Set<String> campaignIds){
            return [SELECT  Id,
                            Name,
                            (SELECT Id, 
                                    Product__c,
                                    Product__r.SAP_Product_Heirarchy__c,
                                    Product__r.ProductCode,
                                    Product_Model__c, 
                                    Customer_Facing_Name__c 
                            FROM Eligible_Product_Line_Items__r
                            WHERE Product__r.ProductCode IN: productCodes),
                            (SELECT Id,
                                    Name,
                                    Eligible_Products__c,
                                    Product_Hierarchies__c,
                                    Start_Date__c,
                                    End_Date__c,
                                    Valid_From__c,
                                    Valid_To__c,
                                    Brand__c,
                                    Country__c
                                    // (SELECT Id, 
                                    //         Customer__c, 
                                    //         Customer_ContactId__c 
                                    // FROM Eligible_Customers__r)       
                            FROM Member_Benefit_Programs__r 
                            WHERE Id IN: campaignIds)
                    FROM Eligible_Products__c
                    WHERE Id IN: eligibleProductIds];  
        }

        public List<Eligible_Customer__c> getEligibleCustomers(Set<String> customerAccountIds){
            return [SELECT  Id,
                            Name,
                            Customer__c,
                            Customer_ContactId__c,
                            Customer_Name__c,
                            Member_Benefit_Program__c,
                            Member_Benefit_Program__r.Name,
                            Member_Benefit_Program__r.Eligible_Products__c,
                            Member_Benefit_Program__r.Product_Hierarchies__c,
                            Member_Benefit_Program__r.Country__c,
                            Member_Benefit_Program__r.Start_Date__c,
                            Member_Benefit_Program__r.End_Date__c,
                            Member_Benefit_Program__r.Valid_From__c,
                            Member_Benefit_Program__r.Valid_To__c,
                            Member_Benefit_Program__r.Brand__c
                    FROM Eligible_Customer__c
                    WHERE Id IN: customerAccountIds];  
        }

        public Map<Id,Member_Benefit_Program__c> getMemberBenefitPrograms(List<String> brands){
            return new Map<Id,Member_Benefit_Program__c> ([ SELECT  Id,
                                                                    Name,
                                                                    Eligible_Products__c,
                                                                    Product_Hierarchies__c,
                                                                    Start_Date__c,
                                                                    End_Date__c,
                                                                    Valid_From__c,
                                                                    Valid_To__c,
                                                                    Brand__c,
                                                                    Country__c, 
                                                                    (SELECT Id, 
                                                                            Customer__c, 
                                                                            Customer_ContactId__c 
                                                                    FROM Eligible_Customers__r)         
                                                            FROM Member_Benefit_Program__c 
                                                            WHERE Brand__c IN: brands]);  
        }

        public List<Asset> getAssets(Set<String> assetIds){
            return [SELECT  Id, 
                            AccountId, 
                            Standard_Warranty_Months__c, 
                            Extended_Warranty_Months__c, 
                            Total_Warranty_Years__c,
                            AssetSource__c,
                            IdentifiedBy__c,
                            ProductDescription,
                            ProductCode,
                            SerialNumber,
                            PurchaseDate,
                            SerialNumberWeek__c, 
                            SerialNumberYear__c,
                            Registered_Date_Formatted__c,
                            Registered_Date_Formula__c,
                            SAPProductHeirarchy__c,
                            Product2.AU_ListPrice__c,
                            Product2.NZ_ListPrice__c,
                            Product2.Category_Customer_Level2__c
                    FROM Asset 
                    WHERE Id IN: assetIds];  
        }

    }   
}