force-app/main/default/objects/Asset/fields/Member_Benefit__c.field-meta.xml
<CustomField>
    <fullName>Member_Benefit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Benefit</label>
    <referenceTo>Member_Benefit__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eligible_Customer__c/Eligible_Customer__c.object-meta.xml
<CustomObject>
    <description>Member Benefit Program: Eligible Customers - Junction Object to link Account and Member Benefit Program</description>
    <label>Eligible Customer</label>
    <nameField>
        <displayFormat>ECN-{00000}</displayFormat>
        <label>Eligible Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligible Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eligible_Customer__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eligible Campaigns</relationshipLabel>
    <relationshipName>Eligible_Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eligible_Customer__c/fields/Customer_ContactId__c.field-meta.xml
<CustomField>
    <fullName>Customer_ContactId__c</fullName>
    <formula>CASESAFEID(Customer__r.PersonContact.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer ContactId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eligible_Customer__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Customer__r.PersonContact.FirstName +&apos; &apos;+ Customer__r.PersonContact.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eligible_Customer__c/fields/Member_Benefit_Program__c.field-meta.xml
<CustomField>
    <fullName>Member_Benefit_Program__c</fullName>
    <label>Member Benefit Program</label>
    <referenceTo>Member_Benefit_Program__c</referenceTo>
    <relationshipLabel>Eligible Customers</relationshipLabel>
    <relationshipName>Eligible_Customers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eligible_Product_Line_Item__c/Eligible_Product_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Eligible Product Line Item</label>
    <nameField>
        <displayFormat>EPPLI-{000000}</displayFormat>
        <label>Eligible Product Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligible Product Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eligible_Product_Line_Item__c/fields/Customer_Facing_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Facing_Name__c</fullName>
    <formula>Product__r.Customer_Facing_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Facing Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eligible_Product_Line_Item__c/fields/Eligible_Product__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Product__c</fullName>
    <label>Eligible Product</label>
    <referenceTo>Eligible_Products__c</referenceTo>
    <relationshipLabel>Eligible Product Line Items</relationshipLabel>
    <relationshipName>Eligible_Product_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eligible_Product_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eligible Product Line Items</relationshipLabel>
    <relationshipName>Eligible_Product_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eligible_Product_Line_Item__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <formula>Product__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Model</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eligible_Products__c/Eligible_Products__c.object-meta.xml
<CustomObject>
    <label>Eligible Products</label>
    <nameField>
        <displayFormat>EP-{000000}</displayFormat>
        <label>Eligible Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligible Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit__c/Member_Benefit__c.object-meta.xml
<CustomObject>
    <label>Member Benefit</label>
    <nameField>
        <displayFormat>MB-{00000}</displayFormat>
        <label>Member Benefit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Member Benefits</relationshipLabel>
    <relationshipName>Member_Benefits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit__c/fields/Member_Benefit_Program__c.field-meta.xml
<CustomField>
    <fullName>Member_Benefit_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Benefit Program</label>
    <referenceTo>Member_Benefit_Program__c</referenceTo>
    <relationshipLabel>Member Benefits</relationshipLabel>
    <relationshipName>Member_Benefits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit__c/fields/Registered_Products__c.field-meta.xml
<CustomField>
    <fullName>Registered_Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Products</label>
    <referenceTo>Eligible_Products__c</referenceTo>
    <relationshipLabel>Member Benefits (Registered Products)</relationshipLabel>
    <relationshipName>Member_Benefits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Further Information Required</fullName>
            </value>
            <value>
                <fullName>Approved - Awaiting Activation</fullName>
            </value>
            <value>
                <fullName>Approved - Activated</fullName>
            </value>
            <value>
                <fullName>Approved - Gift Card Platform Success</fullName>
            </value>
            <value>
                <fullName>Approved - Gift Card Platform Error</fullName>
            </value>
            <value>
                <fullName>Approved - Gift Card Issued</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/Member_Benefit_Program__c.object-meta.xml
<CustomObject>
    <label>Member Benefit Program</label>
    <nameField>
        <label>Member Benefit Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Benefit Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Eligible_Products__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eligible Products</label>
    <referenceTo>Eligible_Products__c</referenceTo>
    <relationshipLabel>Member Benefit Programs</relationshipLabel>
    <relationshipName>Member_Benefit_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Purchase End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Product_Hierarchies__c.field-meta.xml
<CustomField>
    <fullName>Product_Hierarchies__c</fullName>
    <label>Product Hierarchies</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Purchase Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Valid_From__c</fullName>
    <label>Registration Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Program__c/fields/Valid_To__c.field-meta.xml
<CustomField>
    <fullName>Valid_To__c</fullName>
    <label>Registration End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MembershipLoyaltyContoller.cls
/** 
 * @description:        Controller Membership Loyalty Program Automations
 * 
 * @author:             Rexie David
 * @date:               10/3/2023
*/
public with sharing class MembershipLoyaltyContoller {
    
    public static WithoutShare withoutSharing = new WithoutShare();
    
    public static List<Member_Benefit__c> generateMemberBenefits (Set<String> assetIds){

        List<Member_Benefit__c> memberBenefitToInsertList = new List<Member_Benefit__c>();
        List<Asset> registeredProductList = withoutSharing.getAssets(assetIds); // Retrieve Assets (Registered Products)
        Set<String> assetCustomerAccountIds = new Set<String>();
        // Set<String> productCodes = new Set<String>();
        Set<String> eligibleProductIds = new Set<String>();
        List<String> brandSet = new List<String>{'Ryobi'};
        // Map<String,List<memberBenefitProgramWrapper>> memberBenefitProgramWrapMap = new Map<String,List<memberBenefitProgramWrapper>>(); //Member Benefit Id - Member Benefit Wrapper Map
        Map<String,memberBenefitProgramWrapper> memberBenefitProgramWrapMap = new Map<String,memberBenefitProgramWrapper>();
        Map<Id,List<Eligible_Product_Line_Item__c>> memberBenefitProgramEligiblePliMap = new Map<Id,List<Eligible_Product_Line_Item__c>>();
        Map<String,List<Asset>> customerAssetListMap = new Map<String,List<Asset>>();

        //Loop through Registered Products
        for(Asset assetRecord : registeredProductList){
            if(assetRecord.AccountId != NULL) assetCustomerAccountIds.add(assetRecord.AccountId);
            if(customerAssetListMap.containsKey(assetRecord.ContactId)) customerAssetListMap.get(assetRecord.ContactId).add(assetRecord);
            else customerAssetListMap.put(assetRecord.ContactId, new List<Asset> {assetRecord});
        }

        for(Member_Benefit_Program__c memberBenefit : withoutSharing.getMemberBenefitPrograms(brandSet,assetCustomerAccountIds).values()){ //Loop Member_Benefit_Program__c
            if(memberBenefit.Eligible_Customers__r != NULL && memberBenefit.Eligible_Customers__r.size() > 0){

                // memberBenefitProgramWrapper memberBenefitWrap = new memberBenefitProgramWrapper();
                // memberBenefitWrap.memberBenefitProgramRec = memberBenefit;
                // // memberBenefitWrap.customerAssetListMap
                // memberBenefitWrap.exactProductMatch = false;

                Map<String,List<Asset>> filteredCustomerAssetListMap = new Map<String,List<Asset>>(); //Map of CustomerId(Contact Id) - List of Asset();

                for(Eligible_Customer__c eligibleCustomer : memberBenefit.Eligible_Customers__r){ //Loop Eligible_Customer__c
                    if(customerAssetListMap.containsKey(eligibleCustomer.Customer_ContactId__c)){
                        
                        for(Asset assetRec : customerAssetListMap.get(eligibleCustomer.Customer_ContactId__c)){ //Loop through Assets per Eligible Customers
                            DateTime regDateTime = assetRec.Registered_Date_Formula__c;
                            Date regDate = date.newinstance(regDateTime.year(), regDateTime.month(), regDateTime.day());

                            if(meetsDateRange(assetRec,eligibleCustomer)){ //Check if Meet Date Range
                                System.debug(eligibleCustomer.Customer_Name__c + ' meets the date range for ' + eligibleCustomer.Member_Benefit_Program__r.Name + ' by Purchasing '+assetRec.ProductCode+' - '+assetRec.ProductDescription + ' last ' +assetRec.PurchaseDate + ' and Registered it on ' +regDate +'. Campaign Purchase Period starts at '+eligibleCustomer.Member_Benefit_Program__r.Start_Date__c + ' until ' +eligibleCustomer.Member_Benefit_Program__r.End_Date__c +' and Registration Period starts at '+eligibleCustomer.Member_Benefit_Program__r.Valid_From__c + ' until ' + eligibleCustomer.Member_Benefit_Program__r.Valid_To__c);
                                
                                if(filteredCustomerAssetListMap.containsKey(eligibleCustomer.Customer_ContactId__c)){
                                    filteredCustomerAssetListMap.get(eligibleCustomer.Customer_ContactId__c).add(assetRec);
                                }   
                                else{
                                    filteredCustomerAssetListMap.put(eligibleCustomer.Customer_ContactId__c,new List<Asset>{assetRec});
                                }
                                // memberBenefitProgramWrapper memberBenefitWrap = new memberBenefitProgramWrapper(memberBenefit,null,eligibleCustomer,false); //Build memberBenefitProgramWrapper Wrapper
                                
                                // if(memberBenefitProgramWrapMap.containsKey(memberBenefit.Id)){
                                //     memberBenefitProgramWrapMap.get(memberBenefit.Id).add(memberBenefitWrap);
                                // }   
                                // else{
                                //     memberBenefitProgramWrapMap.put(memberBenefit.Id,new List<memberBenefitProgramWrapper>{memberBenefitWrap});
                                // }
                                eligibleProductIds.add(memberBenefit.Eligible_Products__c); 
                            }
                        }
                    }
                }
                if(!filteredCustomerAssetListMap.isEmpty()){
                    memberBenefitProgramWrapper memberBenefitWrap = new memberBenefitProgramWrapper(memberBenefit,filteredCustomerAssetListMap,false); //Build memberBenefitProgramWrapper Wrapper
                    memberBenefitProgramWrapMap.put(memberBenefit.Id,memberBenefitWrap);
                }      
                // if(memberBenefitProgramWrapMap.containsKey(memberBenefit.Id)){
                //     memberBenefitProgramWrapMap.get(memberBenefit.Id).add(memberBenefitWrap);
                // }   
                // else{
                //     memberBenefitProgramWrapMap.put(memberBenefit.Id,new List<memberBenefitProgramWrapper>{memberBenefitWrap});
                // }
            }
        }

        //Retrieve Eligible Products
        for(Eligible_Products__c eligibleProduct : withoutSharing.getEligibleProducts(eligibleProductIds,memberBenefitProgramWrapMap.keySet())){
            
            if(eligibleProduct.Member_Benefit_Programs__r != NULL && eligibleProduct.Member_Benefit_Programs__r.size() > 0
            && eligibleProduct.Eligible_Product_Line_Items__r != NULL && eligibleProduct.Eligible_Product_Line_Items__r.size() > 0){ //Check Member_Benefit_Programs__r and Eligible_Product_Line_Items__r

                for(Member_Benefit_Program__c memberBenefit : eligibleProduct.Member_Benefit_Programs__r){ //Loop Member_Benefit_Program__c under Eligible_Products__c
                    if(memberBenefitProgramWrapMap.containsKey(memberBenefit.Id)){//Check memberBenefit Program if Exist in Wrapper
                        memberBenefitProgramEligiblePliMap.put(memberBenefit.Id,eligibleProduct.Eligible_Product_Line_Items__r);
                    } 
                }
            }
        }

        //Map<String,Member_Benefit__c> customerMemberBenefitMap = new Map<String,Member_Benefit__c>();

        for(String memberBenefitProgramId : memberBenefitProgramWrapMap.keySet()){ //Loop through Member Benefit Program Id

            Set<String> contactProductSet = new Set<String>(); //to check if Product is not duplicated
            
            // Member_Benefit__c memberBenefitToInsert = new Member_Benefit__c(Status__c = 'Submitted', Member_Benefit_Program__c = memberBenefitProgramId); 
            // String memberBenefitProductCode = '';
            memberBenefitProgramWrapper memberBenefitProgramWrap = memberBenefitProgramWrapMap.get(memberBenefitProgramId);

            String currEligibleProductId = memberBenefitProgramWrap.memberBenefitProgramRec.Eligible_Products__c;

            if(memberBenefitProgramWrap.customerAssetListMap != NULL && memberBenefitProgramWrap.customerAssetListMap.keySet().size() > 0){

                for(String customerId : memberBenefitProgramWrap.customerAssetListMap.keySet()){ //Loop through Contact Ids
                    
                    Member_Benefit__c memberBenefitToInsert = new Member_Benefit__c(Status__c = 'Submitted', Member_Benefit_Program__c = memberBenefitProgramId); 
                    String productCodes = '';
                    String currBrand = '';//memberBenefitProgramWrap.assetRec.Brand__c;
                    for(Asset assetRecord : memberBenefitProgramWrap.customerAssetListMap.get(customerId)){
                        //Check asset if assetRecord is an Eligible Product
                        if(memberBenefitProgramEligiblePliMap.get(memberBenefitProgramId) != NULL){
                            if(currBrand == '') currBrand = assetRecord.Brand__c;
                            for(Eligible_Product_Line_Item__c elPli : memberBenefitProgramEligiblePliMap.get(memberBenefitProgramId)){ //Loop through Eligible PLI
                                if(assetRecord.ProductCode == elPli.Product_Model__c){
                                    if(!productCodes.containsIgnoreCase(assetRecord.ProductCode)) productCodes += (productCodes != '') ? ';'+assetRecord.ProductCode : assetRecord.ProductCode;
                                    System.debug('CUSTOMER '+assetRecord.Account.Name + ' MATCH VIA PRODUCT CODE >>> '+ 'eligiblePli.Product_Model__c >>> '+elPli.Product_Model__c + ' assetRecord.ProductCode >>> '+assetRecord.ProductCode);
                                    // eligibleProduct = elPli.Eligible_Product__c; //memberBenefitToInsert.Registered_Products__c = elPli.Eligible_Product__c;
                                    memberBenefitProgramWrap.exactProductMatch = true;
                                    memberBenefitToInsert.Registered_Products__c = currEligibleProductId;
                                }
                            }
                        }

                        if(assetRecord.SAPProductHeirarchy__c != NULL && memberBenefitProgramWrap.memberBenefitProgramRec.Product_Hierarchies__c != NULL 
                        && memberBenefitProgramWrap.memberBenefitProgramRec.Product_Hierarchies__c.containsIgnoreCase(assetRecord.SAPProductHeirarchy__c)){// && memberBenefitProgramWrap.exactProductMatch == false){
                            if(!productCodes.containsIgnoreCase(assetRecord.ProductCode)) productCodes += (productCodes != '') ? ';'+assetRecord.ProductCode : assetRecord.ProductCode;
                            System.debug('CUSTOMER '+assetRecord.Account.Name +' MATCH VIA PRODUCT HIERARCHY >>> '+ 'memberBenefitProgramWrap.memberBenefitProgramRec.Product_Hierarchies__c >>> '+memberBenefitProgramWrap.memberBenefitProgramRec.Product_Hierarchies__c + ' assetRecord.SAPProductHeirarchy__c >>> '+assetRecord.SAPProductHeirarchy__c);
                            // Member_Benefit__c memberBenefitToInsert = new Member_Benefit__c(Status__c = 'Submitted', Brand__c=memberBenefitProgramWrap.assetRec.Brand__c, Member_Benefit_Program__c = memberBenefitProgramId);
                            // memberBenefitToInsert.Customer_Name__c = memberBenefitProgramWrap.assetRec.ContactId;
                            // memberBenefitToInsertList.add(memberBenefitToInsert);
                        }

                    }

                    if(productCodes.length()>0){
                        memberBenefitToInsert.Product_Model__c = productCodes;
                        memberBenefitToInsert.Brand__c = currBrand;
                        memberBenefitToInsert.Customer_Name__c = customerId;
                        memberBenefitToInsertList.add(memberBenefitToInsert);
                    }

                }    
            
            }
            
            //for(memberBenefitProgramWrapper memberBenefitProgramWrap : memberBenefitProgramWrapMap.get(memberBenefitProgramId)){ //Loop Wrapper

                // if(memberBenefitProgramEligiblePliMap.get(memberBenefitProgramId) != NULL){
                    
                //     String currContactId = memberBenefitProgramWrap.assetRec.ContactId;

                //     String currBrand = memberBenefitProgramWrap.assetRec.Brand__c;
                //     String currEligibleProductId = memberBenefitProgramWrap.memberBenefitProgramRec.Eligible_Products__c;
                    
                //     // String eligibleProduct = '';
                //     for(Eligible_Product_Line_Item__c elPli : memberBenefitProgramEligiblePliMap.get(memberBenefitProgramId)){ //Loop through Eligible PLI
                //         if(memberBenefitProgramWrap.assetRec.ProductCode == elPli.Product_Model__c && !contactProductSet.contains(memberBenefitProgramId+memberBenefitProgramWrap.assetRec.ContactId+memberBenefitProgramWrap.assetRec.ProductCode)){
                //             memberBenefitProductCode += (memberBenefitProductCode != '') ? ';'+memberBenefitProgramWrap.assetRec.ProductCode : memberBenefitProgramWrap.assetRec.ProductCode;
                //             contactProductSet.add(memberBenefitProgramId+memberBenefitProgramWrap.assetRec.ContactId+memberBenefitProgramWrap.assetRec.ProductCode);
                //             System.debug('CUSTOMER '+memberBenefitProgramWrap.assetRec.Account.Name + ' MATCH VIA PRODUCT CODE >>> '+ 'eligiblePli.Product_Model__c >>> '+elPli.Product_Model__c + ' memberBenefitProgramWrap.assetRec.ProductCode >>> '+memberBenefitProgramWrap.assetRec.ProductCode);
                //             // eligibleProduct = elPli.Eligible_Product__c; //memberBenefitToInsert.Registered_Products__c = elPli.Eligible_Product__c;
                //             memberBenefitProgramWrap.exactProductMatch = true;
                //         }
                //     }
                    
                //     // memberBenefitToInsert.Member_Benefit_Program__c = memberBenefitProgramId;
                //     // memberBenefitToInsert.Product_Model__c = memberBenefitProductCode;
                //     // memberBenefitToInsert.Brand__c = currBrand;
                //     // memberBenefitToInsert.Registered_Products__c = currEligibleProductId;
                //     // memberBenefitToInsert.Customer_Name__c = currContactId;

                //     // if(customerMemberBenefitMap.containsKey(currContactId)){
                //     //     Member_Benefit__c existMemberBenefit = customerMemberBenefitMap.get(currContactId);
                //     //     existMemberBenefit.Product_Model__c += memberBenefitToInsert.Product_Model__c;
                //     //     customerMemberBenefitMap.put(currContactId,existMemberBenefit);
                //     // } 
                //     // else{
                //     //     customerMemberBenefitMap.put(currContactId,memberBenefitToInsert);
                //     // }

                // }

                // if(memberBenefitProgramWrap.assetRec.SAPProductHeirarchy__c != NULL && memberBenefitProgramWrap.memberBenefitProgramRec.Product_Hierarchies__c != NULL 
                // && memberBenefitProgramWrap.memberBenefitProgramRec.Product_Hierarchies__c.containsIgnoreCase(memberBenefitProgramWrap.assetRec.SAPProductHeirarchy__c) &&
                // memberBenefitProgramWrap.exactProductMatch == false){
                //     System.debug('CUSTOMER '+memberBenefitProgramWrap.assetRec.Account.Name +' MATCH VIA PRODUCT HIERARCHY >>> '+ 'memberBenefitProgramWrap.memberBenefitProgramRec.Product_Hierarchies__c >>> '+memberBenefitProgramWrap.memberBenefitProgramRec.Product_Hierarchies__c + ' memberBenefitProgramWrap.assetRec.SAPProductHeirarchy__c >>> '+memberBenefitProgramWrap.assetRec.SAPProductHeirarchy__c);
                //     Member_Benefit__c memberBenefitToInsert = new Member_Benefit__c(Status__c = 'Submitted', Brand__c=memberBenefitProgramWrap.assetRec.Brand__c, Member_Benefit_Program__c = memberBenefitProgramId);
                //     memberBenefitToInsert.Customer_Name__c = memberBenefitProgramWrap.assetRec.ContactId;
                //     memberBenefitToInsertList.add(memberBenefitToInsert);
                // }
            //}
        }
        // System.debug('customerMemberBenefitMap >>> '+customerMemberBenefitMap);
        System.debug('memberBenefitProgramWrapMap >>> '+memberBenefitProgramWrapMap);
        System.debug('memberBenefitToInsertList.size() >>> '+memberBenefitToInsertList.size());
        System.debug('memberBenefitToInsertList >>> '+memberBenefitToInsertList);
        System.debug('memberBenefitProgramEligiblePliMap >>> '+memberBenefitProgramEligiblePliMap);
        // insert memberBenefitToInsertList;
        return memberBenefitToInsertList;

    }

    private static Boolean meetsDateRange(Asset assetRecord, Eligible_Customer__c eligibleCustomer){

        Boolean meetsDateRange = false;
        DateTime regDateTime = assetRecord.Registered_Date_Formula__c;
        Date regDate = date.newinstance(regDateTime.year(), regDateTime.month(), regDateTime.day());
        if(assetRecord.PurchaseDate >= eligibleCustomer.Member_Benefit_Program__r.Start_Date__c 
        && assetRecord.PurchaseDate <= eligibleCustomer.Member_Benefit_Program__r.End_Date__c
        && regDate >= eligibleCustomer.Member_Benefit_Program__r.Valid_From__c
        && regDate <= eligibleCustomer.Member_Benefit_Program__r.Valid_To__c){
            meetsDateRange = true;
        }
        return meetsDateRange;
    } 

    public class memberBenefitProgramWrapper {
        public Member_Benefit_Program__c memberBenefitProgramRec {get; set;}
        //public Asset assetRec {get; set;}
        public Map<String,List<Asset>> customerAssetListMap {get; set;} 
        public Boolean exactProductMatch {get; set;}
        // public Eligible_Customer__c eligibleCustomerRec {get; set;}
        
        public memberBenefitProgramWrapper(Member_Benefit_Program__c memberBenefitProgramRec, Map<String,List<Asset>> customerAssetListMap, Boolean exactProductMatch){
            this.memberBenefitProgramRec = memberBenefitProgramRec;
            //this.assetRec = assetRec;
            this.customerAssetListMap = customerAssetListMap;
            // this.eligibleCustomerRec = eligibleCustomerRec;
            this.exactProductMatch = exactProductMatch;
        }
    }

    public without sharing class WithoutShare {

        public List<Eligible_Products__c> getEligibleProducts(Set<String> eligibleProductIds, Set<String> campaignIds){
            return [SELECT  Id,
                            Name,
                            (SELECT Id, 
                                    Product__c,
                                    Product__r.SAP_Product_Heirarchy__c,
                                    Product__r.ProductCode,
                                    Product_Model__c, 
                                    Customer_Facing_Name__c,
                                    Eligible_Product__c
                            FROM Eligible_Product_Line_Items__r),
                            (SELECT Id,
                                    Name,
                                    Eligible_Products__c,
                                    Product_Hierarchies__c,
                                    Start_Date__c,
                                    End_Date__c,
                                    Valid_From__c,
                                    Valid_To__c,
                                    Brand__c,
                                    Country__c
                            FROM Member_Benefit_Programs__r 
                            WHERE Id IN: campaignIds)
                    FROM Eligible_Products__c
                    WHERE Id IN: eligibleProductIds];  
        }

        public Map<Id,Member_Benefit_Program__c> getMemberBenefitPrograms(List<String> brands, Set<String> assetCustomerAccountIds){
            return new Map<Id,Member_Benefit_Program__c> ([ SELECT  Id,
                                                                    Name,
                                                                    Eligible_Products__c,
                                                                    Product_Hierarchies__c,
                                                                    Start_Date__c,
                                                                    End_Date__c,
                                                                    Valid_From__c,
                                                                    Valid_To__c,
                                                                    Brand__c,
                                                                    Country__c, 
                                                                    (SELECT Id, 
                                                                            Customer__c, 
                                                                            Customer_ContactId__c,
                                                                            Customer_Name__c,
                                                                            Member_Benefit_Program__r.Start_Date__c,
                                                                            Member_Benefit_Program__r.End_Date__c,
                                                                            Member_Benefit_Program__r.Valid_From__c,
                                                                            Member_Benefit_Program__r.Valid_To__c,
                                                                            Member_Benefit_Program__r.Name
                                                                    FROM Eligible_Customers__r
                                                                    WHERE Customer__c IN: assetCustomerAccountIds 
                                                                    ORDER BY CreatedDate ASC)          
                                                            FROM Member_Benefit_Program__c 
                                                            WHERE Brand__c IN: brands]);  
        }

        public List<Asset> getAssets(Set<String> assetIds){
            return [SELECT  Id, 
                            AccountId,
                            Brand__c,
                            Account.Name, 
                            ContactId,
                            Standard_Warranty_Months__c, 
                            Extended_Warranty_Months__c, 
                            Total_Warranty_Years__c,
                            AssetSource__c,
                            IdentifiedBy__c,
                            ProductDescription,
                            ProductCode,
                            SerialNumber,
                            PurchaseDate,
                            SerialNumberWeek__c, 
                            SerialNumberYear__c,
                            Registered_Date_Formatted__c,
                            Registered_Date_Formula__c,
                            SAPProductHeirarchy__c,
                            Product2.AU_ListPrice__c,
                            Product2.NZ_ListPrice__c,
                            Product2.Category_Customer_Level2__c
                    FROM Asset 
                    WHERE Id IN: assetIds
                    ORDER BY CreatedDate ASC];  
        }

    }   
}